---
- name: "to setup webserver"
  hosts: webservers
  tasks:
    - yum:
       name: httpd
       state: present
    - service:
       name: httpd
       state: started
       enabled: yes
    - template:
       src: index.html
       dest: /var/www/html/index.html
